matrix:
  include:
    - language: java
      dist: trusty
      install: true
      jdk: openjdk9
      before_script:
        - cd Spring-Boot-MockupToHtml/
      script:
        - mvn install -DskipTests

    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required
      before_script:
        - cd Angular-mockupToHtml/
      script: 
        - npm install -g @angular/cli
