matrix:
  include:
    - language: java
      dist: trusty
      install: true
      jdk: openjdk8
      script:
        - mvn install 

    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required
      before_script:
        - cd client/
      script: 
        - npm install -g @angular/cli
